### ISSUE TITLE
Is this available for public consumption?

### ISSUE THREAD

**Issue by danthareja** [bcgov/parks-reso-api#104]
Hey! Super cool to see some public code for BC.

I'm working on a campground availability notifier and was wondering if this system is available to the public, I'd love to support BC campgrounds.

**Comment by danthareja** [comment]
Thanks for the response @rumoncarter!

What I meant previously was actually not if I can fork the project to use my own code (super cool license though), but rather if there is a production version of the API whose data I can consume.

Specifically I'm interested in the data behind https://camping.bcparks.ca/. For example, what campgrounds have sites open on any given date.

Is this something that this project provides? My apologies if not, I just saw 'parks' and 'reso' and got excited.

**Comment by molund** [comment]
Hi @danthareja,

This API is for the BC Parks [Day Use Pass](https://reserve.bcparks.ca/dayuse/) system. It is a back-end for two Angular projects, and so far there is no documentation for public consumption.
1. https://github.com/bcgov/parks-reso-public
2. https://github.com/bcgov/parks-reso-admin

The new camping reservation system is created and maintained by https://www.camis.com/, and it isn't integrated with the Day Use Pass system.

**Comment by danthareja** [comment]
Ahh -- the Day Use Pass is the part I was missing. Thanks for filling in the gap @molund :)
