### ISSUE TITLE
[XL] Connect Day Use Pass to Park Name Data Register

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-api#288]
As a member of the public I would like to see accurate park names when booking a day use pass so that I know I am booking at the right place, have the right information, and can view indigenous characters where they exist.

As a DUP admin user, I would like to have all park names in DUP automatically update if they are changed and show the correct spelling and indigenous characters so that I do not have to manually change the name.

**Acceptance Criteria:**

- Day Use Pass Public displays the park name from the park name register (display name)
- Day Use Pass Admin displays the park name from the park name register (display name)
- If the park name is changed in the register, then DUP public and admin shows the updated name
- Where applicable, indigenous characters are displayed correctly

**Notes**
- Blocked by [#10](https://github.com/bcgov/parks-data-register/issues/10)
- - need vanity url for DUP to access the data register API.
- Blocked by https://github.com/bcgov/parks-data-register/issues/97
- - link on ORCS number to get correct park
- Also blocked by: https://github.com/bcgov/parks-data-register/issues/23
- demo for this ticket will include changing the park name via register (likely via backend not through UI) and then having it update in DUP admin and public
- from (https://github.com/bcgov/parks-data-register/issues/97)
_For Public: There are no changes to make as the data feed for parks all comes from the api.

For Admin:

On Edit the Park Name field needs to be turned into a non-modifiable field, just how the Park ORCS field works.
If DUP adds a 'New Park' feature, the admin page should show a search page that queries the data register. This way the user can pick based on name/orcs/etc and that is used to see the park name in the back-end of the DB.

For API:

The general idea is to cache the data from the data register overnight and keep all queries for DUP locked into the DUP API.

nightly job to query the data register should query based on orcs and update the park name field when a change is detected on the pk: park. Facilities do not need to be updated as they do not have the name property on their object.
Existing passes don't need to be changed as the key is off of orcs. Their display name can remain 'old' and will not have an impact other than the display name field being out of date. It is not very performant to update the 100,000's of records with the new name.
Facilities will need to be updated to use an identifier as opposed to keying off of name if the data register starts to serve out those names.
The reservations object needs to be converted to use the orcs identifier in the PK instead of the name. Currently it is reservations::<name>::<facility> This is a breaking change that will need to be done before we allow name changes to happen.
In doing the reservation object change, a displayName field should be attached to the object as it currently only exists on the pk. See writeFacility, writeModifier, writePass lambda functions.
Data model for DUP should be created and stored in a NoSQL Workbench file and committed to the repository.
Future improvements for the data register are to build a push mechanism to tell DUP to update as opposed to having DUP poll nightly._

**Questions**

**Comment by cameronpettit** [comment]
Blocked by[#10](https://github.com/bcgov/parks-data-register/issues/10). Vanity URL needed so DUP knows were to look for API.

**Comment by JLWade** [comment]
Unblocked #10

**Comment by manuji** [comment]
@JLWade , should we disable the ability to edit the Park name on the DUP Admin?

**Comment by manuji** [comment]
Created the ticket for the issue with Park name field: https://github.com/bcgov/parks-reso-admin/issues/311

@cameronpettit , how long does it take to get the changes done on DynamoDB to reflect on DUP-ADMIN and DUP-Public? (after a hard refresh)

**Comment by cameronpettit** [comment]
@manuji The cronjob runs at midnight each night. Or you can invoke the `updateParkNames` lambda directly from the web console.

**Comment by manuji** [comment]
Thanks @cameronpettit , as the forced run of the cron job didn't work, I will wait and see if this is going to update after midnight.

**Comment by manuji** [comment]
Tested on TEST: Failed
* Tested with Golden Ears Park and the changes made on the DynamoDB won't reflect on the DUP-Public & Admin. 

FYI @marklise & @cameronpettit

**Comment by cameronpettit** [comment]
This ticket was moved to QA before our Authorizer code landed. Axios calls now require an `Authorizer: None` header in the request - currently this is not present in the fetch call. 
Adding in this header will likely fix the issue.

**Comment by cameronpettit** [comment]
Will fix the issue in the previous comment but moving to blocked as we need the vanity URL sorted before we are able to 100% complete this ticket

**Comment by manuji** [comment]
Tested on TEST: **Passed** ✅
* verified that this task has been implemented and working fine. 
* Passing to PO review. 


![Image](https://github.com/bcgov/parks-reso-api/assets/65190263/86bbc954-e1df-466a-908d-82121b1bba8f)



![Image](https://github.com/bcgov/parks-reso-api/assets/65190263/2c2831dc-0a18-4a14-aad4-886f95b80cf6)

**Comment by JLWade** [comment]
moving to done
