### ISSUE TITLE
[XL] Move DUP from Terraform to SAM

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-api#336]
**Description**
Goal is to be able to deploy DUP (admin, public, and api) via SAM without the use of any terraform.

**Acceptance Criteria**
- [ ]  Full smoke test to make sure everything ported over properly
  - [ ] DUP Public
  - [ ] DUP Admin
  - [ ] DUP API

**Dev checklist**
- [ ]  lookup how we do this in Data Register
- [ ]  Everything that is AWS side (ie. database, Cloudfront distributions, logs, S3,etc) will need to be setup in SAM
- [ ]  Implement DynamoDB layers
- [ ]  Write github actions so you can deploy it automatically when you do a change

**Comment by Dianadec** [comment]
@Christopher-walsh22  to add notes about the progress of this card at the time of iceboxing it.

**Comment by Dianadec** [comment]
holding off on merging this work until the hold pass timer is done.

**Comment by Christopher-walsh22** [comment]
In the process of doing this SAM transition the steps identified for completion were as follows: 

-Converting layers to SAM
-Converting Lambdas to SAM
-Converting Tests to SAM 
-Removing Terraform

All of this has been completed for DUP now. Instead of creating more tickets it seemed best to just leave a comment on this one.

**Comment by manuji** [comment]
Tested on https://test-dup.bcparks.ca/dayuse/: Pending
1. The version on site footer shows "gitHubHash" instead of the version number. 
![Image](https://github.com/user-attachments/assets/dc8f4907-1c60-438b-8c29-b945c551ec3c)
2.

**Comment by Christopher-walsh22** [comment]
@manuji I have created 2 PRs to address these issues. The version bug you highlighted was actually part of the DUP-PUBLIC deployment. But I have linked the PR to this ticket to keep everything organized until the bugs are resolved. I will keep you updated for when we can move the fixes to TEST.

**Comment by manuji** [comment]
Tested on TEST: Pending
* Verified that most of the bugs are now fixed except for the emails. @Christopher-walsh22 I still don't get emails from Test environment when booking passes. Could you please help me figure why it's not working for me? I am still using the same email address I use before.,

**Comment by manuji** [comment]
@Christopher-walsh22 , I am still not getting emails from the TEST. I couldn't try this on Dev as I am getting the error given below from cloudflare. 
![Image](https://github.com/user-attachments/assets/a0737a4d-17e6-417a-aaba-e4d4962dda85)

**Comment by manuji** [comment]
Tested on TEST: **Pending**
* verified that the emails are now received. 
* Pending testing the SMS reminders.

**Comment by LindsayMacfarlane** [comment]
Thank you for all your work on this @Christopher-walsh22 ! I'm still digging through things, but the main things I've found:

- really slow load of 'all parks' for the analytics/metrics
- booking issues related to the 7 am booking stuff (being dealt with through a different ticket)

I feel I've dug through most aspects of the site for both Admin and Public.

**Comment by LindsayMacfarlane** [comment]
Re-tested this am for the site metrics (12 months) - still seems slow, but much faster response than yesterday. Thank you @Christopher-walsh22 !

@MarshallHenson - You know this system so much better than me - would you be able to test out both the public and admin sites in TEST to make sure things meet you expectations? I took a pretty deep dive yesterday and left comments on a couple possible issues I discovered (see previous comment) and would love an extra set of eyes as the change to SAM affects the entire system. Thank you!

**Comment by MarshallHenson** [comment]
It is actually very rare that I would pull 12 months of data, as we keep a "source of truth" Excel sheet for the data on Teams and update it frequently (ish). So I don't have a great frame of reference but I don't have any concerns with how quickly it just loaded for me.

**Comment by LindsayMacfarlane** [comment]
@Christopher-walsh22 - double checking before closing - feel we are good to go?

**Comment by Christopher-walsh22** [comment]
@LindsayMacfarlane  I would say yes on this ticket. But in order to release this everything in TEST will need to be approved as well. It looks like the only one that may be holding things back is passes bookable prior to 7am. @manuji might be able to give a better timeline of when this can be released, but I'm excited to finally have this one checked off :)

**Comment by LindsayMacfarlane** [comment]
Thank you for that clarification @Christopher-walsh22 ! Marking ticket as closed - with the understanding before releasing to PROD, everything in test needs to be ready :)
