### ISSUE TITLE
DUP - Make changes for Daylight Saving Time starting March 10th

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-api#352]
On March 10, 2024, the Day Light Savings will start and we need to make changes to the times that cron jobs are running and passes are switching status.

**Acceptance Criteria:**
- cronjob for warmup function starts at 7am March 10th, 2024 and beyond
- reminder emails and SMS messages sent at 4pm
- AM passes expire at 12pm
- PM passes expire at 6pm 
  - cron job that changes passes to expire: https://github.com/bcgov/parks-reso-api/issues/346 

Notes:
- reference https://github.com/bcgov/parks-reso-api/issues/314 for how this was done in the fall

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that the AM pass I booked expired at 12pm. Rest of the scenarios will be tested through out the day. 
* We will deploy this change to PROD at 1pm. 
* Passing to PO review.

**Comment by JLWade** [comment]
Moving to done :)
