### ISSUE TITLE
[L] Security - Hold Pass Timer

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-reso-api#360]
#### Description:

Need to ensure people don't abuse DUP
Concept of a web session 
- with lambda @ edge, we can do more. 
- Must push all API calls through the vanity url (This ensures we can determine whether the api call is from a valid web session)
  - Will allow someone to not smash our backend
  - look at web application firewall (WAF) - bot control feature (includes automatic captcha)
   - Amazon - detect unusual traffic. on certain calls coming in and amazon flags it, your code plus amazon talking together can push a captcha (eg) that is outside the application - better way of dealing with these kinds of issues. - cost associated. but provides ultimate security. Cost is based on number of hits to get.
  - Rate limiting (don't want people button smashing) - BEHAVE PPL COME ON
  - Policy thing - might want to be able to tie certain IP ranges from holding a set number of passes. Problems: Might originate from the same IP if in the same spot.
    - Marshall talked to Jess about limiting the number of passes from the same email
    - edge case: One person had 15 diff emails
    - need to evaluate unintended consequences 
Note: need to still review logs, traffic, inspect it, as a manual review of anomalies.

#### Acceptance Criteria:
See description and dev checklist.

#### Development Checklist:

- [ ] Create session context w.r.t. site and lambda@edge function logic.  Prevent access to API otherwise.
- [ ] Configure WAF appropriately

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by JLWade** [comment]
blocked until API tickets are further along

**Comment by Dianadec** [comment]
During refinement we added a point in the dev checklist to configure WAF
