### ISSUE TITLE
[M] Health check on GC Notify

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-api#368]
#### Description:
We received an alert from GC notify about the bulk email service. This ticket is to look into that alert and do a general health check on GC notify for test and prod services. 

![Image](https://github.com/bcgov/parks-reso-api/assets/38668130/e738a2ce-367d-4f2c-98d7-616bc38d9fbf)

#### Acceptance Criteria:

- [ ] Confirmation and reminder emails are sending as expected from DUP test instance
- [ ] Confirmation and reminder emails are sending as expected from DUP prod instance
- [ ] Update alert to show which environment the error is occurring in
- [ ] Update alert notification to show in dev channel or alerts channel instead of archived channel

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- alert is probably coming from test because no emails are being sent in prod
-

**Comment by Christopher-walsh22** [comment]
Initial research shows this alert is coming from the DEV environment.

**Comment by Christopher-walsh22** [comment]
DEV is hooked up to GCNotify it is the same account used as TEST. It looks like this might be related to some refactoring a few days ago.

From what I can tell no emails or texts can be sent right now. We should probably avoid any releases until this is figured out. @JLWade

**Comment by JLWade** [comment]
good call! 
@Christopher-walsh22  Can you post that in the dev channel? Then once this ticket is complete we can deploy DUP again

**Comment by JLWade** [comment]
tested booking and cancelling in prod - working as expected - moving to done
