### ISSUE TITLE
Spike: Sort out plan for AWS Migration

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-reso-api#406]
#### Description:
**This ticket it to sort out a plan and make all necessary tickets needed to implement the required AWS migration.**

OCIO is upgrading landing zones in AWS, switching from AWS Secure Environment Accelerator (ASEA) product from the Government of Canada to the Landing Zone Accelerator (LZA) product from AWS. 
 
The ASEA is the codebase currently used to configure and deploy our landing zone where your project-sets are hosted. The LZA is a new codebase that is the successor to the ASEA. It is built to align with AWS security best practices, conform with multiple global compliance frameworks and meet government requirements for security. 
 
The ASEA codebase will be deprecated as of summer 2025 and will no longer receive updates or security fixes. The LZA codebase is officially supported by the AWS vendor who provides security patches, hot fixes, and new releases for the codebase. Switching to the LZA codebase for the AWS Landing zone will ensure that applications continue to run in a secure and compliant environment. 

There is no migration path for the in-place upgrade of the ASEA landing zone to LZA. Therefore, OICO will build a separate LZA-based landing zone in parallel with the existing ASEA-based landing zone and we will be required to migrate our applications into the new landing zone. 
  
It is recommended that to prepare, we:
- Test application disaster recovery mechanism (for example, data backup and recovery) - DONE - see comments
- Develop CI/CD for deploying application using an Infrastructure as Code (IaC) approach  - DONE - see comments 
 
OCIO is aiming to allow project migrations to start by the end of Q3 2024/25. More information available at #aws-tenant-requests in rocketchat or cloud.pathfinder@gov.bc.ca

#### Acceptance Criteria:
[Note: Use 'Given/When/Then' format if it makes sense to. Otherwise, a simple checklist that can be tested.]

- [x] Complete Platform Services 'ready for migration' survey
- [x] tickets for implementation of this migration are created
- [x] tickets and plan cover all Osprey products (A&R, DUP, DR, Backcountry) 

#### Development Checklist:

- [ ] ...
- [ ] ...
- [ ] ...

#### Dependencies

- Blocked by
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by meyerdarcie** [comment]
Who is deprecating the ASEA?
- The ASEA is a piolet project headed by AWS. They are deprecating the project which means that they will no longer be releasing updates. We can still operate the ASEA after deprecation, however the new officially supported service is the LZA.

What is different between LZA and ASEA, is there open documentation available to consume/gain visibility into the infrastructure setup?
- The main difference is that LZA is an AWS service, while the ASEA is an AWS project. There will be much more support coming with the LZA but the LZA is designed based on the ASEA, so the infrastructure is largely the same. This is a chance for us to improve on our design in a few ways. I don’t think we have written documentation on the transition yet, but please attend the community updates as we’ll be updating there with more details as they come. To see the recording of our last community update please check out the ”CloudPathfinder Community Update” channel in teams.

**Comment by Dianadec** [comment]
Let's confirm what the actual date/deadline is - or when we can actually start this. When will the accounts be ready?
Daniel recommends this order: Reservations, Name register, A&R, DUP
cc @JLWade

**Comment by JLWade** [comment]
cloud pathfinder team will not have LZA spaces ready until the new year so will likely not be able to take a look at this one until then to see what is needed. Recommend moving this one out due to that - @LindsayMacfarlane @Dianadec

**Comment by LindsayMacfarlane** [comment]
Thanks @JLWade! We will pull this ticket out and wait until later to action :)

**Comment by LindsayMacfarlane** [comment]
November 25 - no real timeline as of yet - simply in the 'new year'. Follow-up required.

**Comment by Dianadec** [comment]
todo: try to get the account as soon as possible - clarify things in emails with Lindsay. @LindsayMacfarlane  could you loop me in to the emails via forwards?

**Comment by marklise** [comment]
@Dianadec test

**Comment by Dianadec** [comment]
AWS team meeting notes Dec 10:

- Least risky would be Data register.
- DUP would take the longest - most complex - most .
- Todo: setup Separate migration tickets per product.

If [they] have the migration account ready, then we can start planning out what we are going to do and when.

**Comment by LindsayMacfarlane** [comment]
Tickets for each product's migration: 
<html>
<body>
<html><head></head><body>
AWS Migration [Data Register]
--
AWS Migration [Day Use Pass]
AWS Migration [A&R]
AWS Migration [Reservations]

</body></html>
</body>
</html>[AWS Migration [Data Register]](https://github.com/bcgov/parks-data-register/issues/554)	https://github.com/bcgov/parks-data-register/issues/554
[AWS Migration [Day Use Pass]](https://github.com/bcgov/parks-reso-api/issues/431)	https://github.com/bcgov/parks-reso-api/issues/431
[AWS Migration [A&R]](https://github.com/bcgov/bcparks-ar-admin/issues/418)	https://github.com/bcgov/bcparks-ar-admin/issues/418
[AWS Migration [Reservations]](https://github.com/bcgov/reserve-rec-public/issues/85)	https://github.com/bcgov/reserve-rec-public/issues/85

**Comment by Dianadec** [comment]
There is no longer an urgency to get this done since the platform team isn't ready yet and March seems to be the timeframe that we'll need to wait for.  @LindsayMacfarlane  I think we can move this to done? I can make an Epic for the migration to contain all the tickets, and capture notes from this spike ticket in that epic.

**Comment by Dianadec** [comment]
@LindsayMacfarlane  to add to my comment above, I noticed at the end of this ticket description, there are two bullets in terms of how to prepare - do we need specific tickets for these? I will also post in dev chat to ask the team.

> It is recommended that to prepare, we:

> Test application disaster recovery mechanism (for example, data backup and recovery)
> Develop CI/CD for deploying application using an Infrastructure as Code (IaC) approach

**Comment by Dianadec** [comment]
In response to the second bullet above re: CI/CD, cam said: I think we do this already - this speaks to SAM/CDK templates and Github Actions deployments. Basically - someone without intricate knowledge of our devops infrastructure can still deploy code changes because we've mostly automated our CI/CD.

Therefore, I'll move this ticket to PO review.

**Comment by LindsayMacfarlane** [comment]
Moving to done.
