### ISSUE TITLE
Go back to PST

### ISSUE THREAD

**Issue by Christopher-walsh22** [bcgov/parks-reso-api#421]
2024 Day Light Savings is over we need to make changes to the times that cron jobs are running and passes are switching status at appropriate time.

Acceptance Criteria:

cronjob for warmup function starts at 6am
reminder emails and SMS messages sent at 4pm
AM passes expire at 12pm
PM passes expire at 6pm

reference: [Ticket 314](https://github.com/bcgov/parks-reso-api/issues/314)

**Comment by manuji** [comment]
Tested on TEST:
* Verified that the reminder emails and SMS sent at 4pm. 
* Pending verification of AM pass expiry at 12 pm
* Pending verification of PM pass expiry at 6pm.

**Comment by manuji** [comment]
@Christopher-walsh22 , small update: I tried checking the pass on Admin side and it still says Reserved and not Active even after 1 pm.

**Comment by manuji** [comment]
Tested on Alpha-test:
* Book a PM pass before 12 pm and check if status change to Active after 12 pm.
*

**Comment by LindsayMacfarlane** [comment]
@manji approved. It will take a while for me to test and I trust your testing and happy to approve.
